server:
  port: 8040

spring:
  application:
    name: mall-customer-service  #微服务名称

  cloud:
    nacos:
      discovery:   #配置nacos注册中心地址
        server-addr: localhost:8848
        #server-addr: 192.168.65.174:8848,192.168.65.192:8848,192.168.65.204:8848
        namespace: dev
        #        group: tulingshop
        #        ephemeral: false
        username: nacos
        password: nacos