server:
  port: 8055

spring:
  application:
    name: mall-order-service  #微服务名称

  cloud:
    nacos:
      discovery:  #配置nacos注册中心地址
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: dev

